export const errorsNames = {
  SILENT: 'SILENT',
  REDIRECT: 'REDIRECT',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION: 'VALIDATION',
  WRONG_DATA: 'WRONG_DATA',
  NOT_ALLOWED: 'NOT_ALLOWED',
  AXIOS_ERROR: 'AXIOS_ERROR',
  VALIDATION_CUSTOM: 'VALIDATION_CUSTOM',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  WS_ERROR_DATA: 'WS_ERROR_DATA',
  WS_ERROR_LOST: 'WS_ERROR_LOST',
  ERROR_ADD_TO_CART: 'ERROR_ADD_TO_CART',
} as const;
