export const system = {
  INPUT_MAX_LENGTH: 250,
  TEXTAREA_MAX_LENGTH: 8000,
  NOTIFICATION_LEAVING_TIMEOUT: 300,
  SPACE_BEFORE_INPUT_TOP_OFFSET: 90,
  MARKER_ANIMATION_DURATION: 400,
  MODALS_BASE_Z_INDEX: 1000,
  MODALS_LEAVING_TIMEOUT: 200,
  NOTIFICATIONS_BASE_Z_INDEX: 1001,
  MODALS_SHAKING_TIMEOUT: 500,
  NOTIFICATIONS_LEAVING_TIMEOUT: 200,
  TEXTAREA_DEFAULT_ROWS: 4,
  SMOOTH_SCROLL_DURATION: 600,
} as const;
